"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, Plus, Trash2 } from "lucide-react";
import "./formulas.css";

type Formula = { id: number; subject: string; category: string; expression: string; explanation: string };
const starter: Formula[] = [
  { id: 1, subject: "Physics", category: "Mechanics", expression: "F = ma", explanation: "Force equals mass multiplied by acceleration." },
  { id: 2, subject: "Physics", category: "Mechanics", expression: "v = u + at", explanation: "Final velocity for constant acceleration." },
  { id: 3, subject: "Physics", category: "Thermodynamics", expression: "PV = nRT", explanation: "The ideal gas law." },
];
export default function FormulasPage() { const [items, setItems] = useState<Formula[]>(starter); const [form, setForm] = useState({ subject: "Physics", category: "Mechanics", expression: "", explanation: "" }); const [ready, setReady] = useState(false); useEffect(() => { try { const saved = localStorage.getItem("pos.formulas"); if (saved) setItems(JSON.parse(saved)); } finally { setReady(true); } }, []); useEffect(() => { if (ready) localStorage.setItem("pos.formulas", JSON.stringify(items)); }, [items, ready]); const add = () => { if (form.expression.trim()) { setItems(value => [...value, { id: Date.now(), ...form }]); setForm({ ...form, expression: "", explanation: "" }); } }; const subjects = [...new Set(items.map(item => item.subject))]; return <main className="formula-page"><a href="/" className="back"><ArrowLeft size={16}/> Personal OS</a><p>KNOWLEDGE</p><h1>Formula cheatsheet</h1><span>Keep high-value formulas linked to a subject and short explanation.</span><div className="formula-grid"><section>{subjects.map(subject => <section className="formula-card" key={subject}><h2>{subject}</h2>{[...new Set(items.filter(item => item.subject === subject).map(item => item.category))].map(category => <div key={category}><h3>{category}</h3>{items.filter(item => item.subject === subject && item.category === category).map(item => <article key={item.id}><b>{item.expression}</b><p>{item.explanation || "No explanation yet."}</p><button onClick={() => setItems(value => value.filter(current => current.id !== item.id))}><Trash2 size={13}/> Delete</button></article>)}</div>)}</section>)}</section><aside className="formula-card"><h2>Add formula</h2><label>Subject<input value={form.subject} onChange={event => setForm({ ...form, subject: event.target.value })}/></label><label>Category<input value={form.category} onChange={event => setForm({ ...form, category: event.target.value })}/></label><label>Formula<input value={form.expression} onChange={event => setForm({ ...form, expression: event.target.value })} placeholder="e.g. E = mc²"/></label><label>Explanation<textarea value={form.explanation} onChange={event => setForm({ ...form, explanation: event.target.value })}/></label><button className="add" onClick={add}><Plus size={16}/> Add formula</button></aside></div></main>; }
