"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, Brain, Check, Eye, Plus, RotateCcw } from "lucide-react";
import { createSupabaseBrowserClient } from "../../lib/supabase-browser";
import "./flashcards.css";

type Card = { id: number; question: string; answer: string; topic: string; due: string; dueAt?: string; lastRating?: string };
const example: Card[] = [{ id: 1, question: "What is a JavaScript closure?", answer: "A function bundled with its lexical environment.", topic: "Functions", due: "Today", dueAt: new Date().toISOString() }];

export default function FlashcardsPage() {
  const [cards, setCards] = useState<Card[]>(example); const [index, setIndex] = useState(0); const [revealed, setRevealed] = useState(false);
  const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [topic, setTopic] = useState("General"); const [ready, setReady] = useState(false); const [cloud, setCloud] = useState(false);
  useEffect(() => { let active = true; const load = async () => { let local = example; try { const saved = localStorage.getItem("pos.cards"); if (saved) local = JSON.parse(saved); } catch {} const client = createSupabaseBrowserClient(); if (!client) { if (active) { setCards(local); setReady(true); } return; } const { data: user } = await client.auth.getUser(); if (!user.user) { if (active) { setCards(local); setReady(true); } return; } const result = await client.from("flashcards").select("id,question,answer,topic,due,due_at,last_rating").order("created_at"); if (result.error) { if (active) { setCards(local); setReady(true); } return; } if (!result.data?.length && local.length) { const inserted = await client.from("flashcards").insert(local.map(item => ({ user_id: user.user.id, question: item.question, answer: item.answer, topic: item.topic, due: item.due, due_at: item.dueAt ?? new Date().toISOString(), last_rating: item.lastRating ?? null }))).select("id,question,answer,topic,due,due_at,last_rating"); if (inserted.data?.length) result.data = inserted.data; } if (active) { setCards((result.data ?? []).map(item => ({ id: item.id, question: item.question, answer: item.answer, topic: item.topic, due: item.due, dueAt: item.due_at, lastRating: item.last_rating ?? undefined }))); setCloud(true); setReady(true); } }; void load(); return () => { active = false; }; }, []);
  useEffect(() => { if (ready && !cloud) localStorage.setItem("pos.cards", JSON.stringify(cards)); }, [cards, ready, cloud]);
  const dueCards = cards.filter(item => !item.dueAt || new Date(item.dueAt).getTime() <= Date.now());
  const card = dueCards[index];
  const rate = (rating: string) => { if (!card) return; const minutes = rating === "Again" ? 10 : rating === "Hard" ? 24 * 60 : rating === "Good" ? 3 * 24 * 60 : 7 * 24 * 60; const dueAt = new Date(Date.now() + minutes * 60 * 1000).toISOString(); const due = minutes < 60 ? "In 10 minutes" : rating === "Hard" ? "Tomorrow" : `In ${Math.round(minutes / (24 * 60))} days`; setCards(items => items.map(item => item.id === card.id ? { ...item, due, dueAt, lastRating: rating } : item)); if (cloud) void createSupabaseBrowserClient()?.from("flashcards").update({ due, due_at: dueAt, last_rating: rating }).eq("id", card.id); setRevealed(false); setIndex(0); };
  const add = async () => { if (question.trim() && answer.trim()) { const draft = { question: question.trim(), answer: answer.trim(), topic: topic.trim() || "General", due: "Today", dueAt: new Date().toISOString() }; if (cloud) { const client = createSupabaseBrowserClient(); const { data: user } = await client!.auth.getUser(); const result = user.user ? await client!.from("flashcards").insert({ user_id: user.user.id, question: draft.question, answer: draft.answer, topic: draft.topic, due: draft.due, due_at: draft.dueAt }).select("id").single() : null; if (result?.data) setCards(items => [...items, { ...draft, id: result.data.id }]); } else setCards(items => [...items, { ...draft, id: Date.now() }]); setQuestion(""); setAnswer(""); } };
  return <main className="recall"><a href="/" className="back"><ArrowLeft size={16}/> Personal OS</a><header><div><p>ACTIVE RECALL</p><h1>Flashcards</h1><span>Test understanding, then decide when to review again.</span></div><div className="count"><Brain size={18}/>{cards.length} cards</div></header><section className="recall-grid"><section className="card-stage"><div className="review-head"><span>DUE NOW · {dueCards.length}</span><span>{dueCards.length ? index + 1 : 0}/{dueCards.length}</span></div>{card ? <><div className="flashcard"><small>{card.topic}</small><h2>{card.question}</h2>{revealed && <div className="answer">{card.answer}</div>}</div>{revealed ? <div className="ratings">{["Again", "Hard", "Good", "Easy"].map(item => <button key={item} onClick={() => rate(item)}>{item}</button>)}</div> : <button className="reveal" onClick={() => setRevealed(true)}><Eye size={16}/> Reveal answer</button>}</> : <p>{cards.length ? "Nothing is due right now—come back later." : "No cards yet—create the first one below."}</p>}</section><section className="new-card"><h2>Create a card</h2><label>Question<input value={question} onChange={event => setQuestion(event.target.value)} placeholder="What do you want to remember?"/></label><label>Answer<textarea value={answer} onChange={event => setAnswer(event.target.value)} placeholder="Write the answer in your own words..."/></label><label>Topic<input value={topic} onChange={event => setTopic(event.target.value)} placeholder="e.g. Functions"/></label><button className="create" onClick={add}><Plus size={16}/> Add flashcard</button></section></section><section className="queue"><h2>Review queue</h2><p><b>{dueCards.length}</b> due now</p><p><b>{cards.filter(item => item.lastRating === "Again").length}</b> need another attempt</p><button onClick={() => { setIndex(0); setRevealed(false); }}><RotateCcw size={15}/> Restart review</button></section></main>;
}
