"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, BookOpen, Plus, Trash2 } from "lucide-react";
import "./subjects.css";

type Topic = { id: number; name: string; subject: string; progress: number };
const starter: Topic[] = [{ id: 1, name: "Functions", subject: "JavaScript", progress: 82 }, { id: 2, name: "Arrays", subject: "JavaScript", progress: 64 }];
export default function SubjectsPage() { const [topics, setTopics] = useState<Topic[]>(starter); const [subject, setSubject] = useState("JavaScript"); const [topic, setTopic] = useState(""); const [ready, setReady] = useState(false); useEffect(() => { try { const saved = localStorage.getItem("pos.topics"); if (saved) setTopics(JSON.parse(saved)); } finally { setReady(true); } }, []); useEffect(() => { if (ready) localStorage.setItem("pos.topics", JSON.stringify(topics)); }, [topics, ready]); const add = () => { if (subject.trim() && topic.trim()) { setTopics(items => [...items, { id: Date.now(), subject: subject.trim(), name: topic.trim(), progress: 0 }]); setTopic(""); } }; const subjects = [...new Set(topics.map(item => item.subject))]; const removeSubject = (name: string) => { if (window.confirm(`Delete ${name} and all its syllabus topics?`)) setTopics(items => items.filter(item => item.subject !== name)); }; return <main className="subjects"><a href="/" className="back"><ArrowLeft size={16}/> Personal OS</a><p>LEARN</p><h1>Subjects & syllabus</h1><span>Shape the curriculum around what you actually study.</span><section className="add-subject"><input value={subject} onChange={event => setSubject(event.target.value)} placeholder="Subject name"/><input value={topic} onChange={event => setTopic(event.target.value)} onKeyDown={event => event.key === "Enter" && add()} placeholder="First syllabus topic"/><button onClick={add}><Plus size={16}/> Add topic</button></section><div className="subject-list">{subjects.map(name => <section className="subject-card" key={name}><header><div><BookOpen size={17}/><h2>{name}</h2></div><button onClick={() => removeSubject(name)}><Trash2 size={15}/> Delete subject</button></header>{topics.filter(item => item.subject === name).map(item => <div className="syllabus" key={item.id}><span>{item.name}</span><small>{item.progress}% complete</small><button aria-label={`Delete ${item.name}`} onClick={() => setTopics(items => items.filter(current => current.id !== item.id))}><Trash2 size={13}/></button></div>)}</section>)}{!subjects.length && <p className="empty">No subjects yet. Add your first syllabus topic above.</p>}</div></main>; }
