"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, ExternalLink, Plus, Trash2 } from "lucide-react";
import "./media.css";
import "./hubs.css";
type Media={id:number;title:string;type:"Movie"|"Anime"|"Manga"|"Game";status:"Want"|"In Progress"|"Completed"|"Dropped"};
const hubs=[{title:"Anime & Manga",links:[{label:"Anime Tracker / Stream",url:"https://www.miruro.ru/"},{label:"Manga Reader",url:"https://comix.to/home"}]},{title:"Movies & Music",links:[{label:"Movies",url:"https://www.rivestream.app/"},{label:"Music",url:"https://monochrome.tf/"}]},{title:"Gaming",links:[{label:"Game Launchers",url:"https://www.crazygames.com/"}]}];
export default function MediaPage(){const[items,setItems]=useState<Media[]>([]),[title,setTitle]=useState(""),[type,setType]=useState<Media["type"]>("Movie"),[ready,setReady]=useState(false);useEffect(()=>{try{const s=localStorage.getItem("pos.media");if(s)setItems(JSON.parse(s))}finally{setReady(true)}},[]);useEffect(()=>{if(ready)localStorage.setItem("pos.media",JSON.stringify(items))},[items,ready]);const add=()=>{if(title.trim()){setItems(x=>[{id:Date.now(),title:title.trim(),type,status:"Want"},...x]);setTitle("")}};return <main className="media"><a href="/" className="back"><ArrowLeft size={16}/> Personal OS</a><p>MEDIA</p><h1>Entertainment hub</h1><span>Launch media services and keep your personal list in one place.</span><div className="hub-grid">{hubs.map(hub=><section className="hub" key={hub.title}><h2>{hub.title}</h2>{hub.links.map(link=><a key={link.url} href={link.url} target="_blank" rel="noreferrer">{link.label}<ExternalLink size={14}/></a>)}</section>)}</div><section className="add"><input value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="Add a title to your list..."/><select value={type} onChange={e=>setType(e.target.value as Media["type"])}><option>Movie</option><option>Anime</option><option>Manga</option><option>Game</option></select><button onClick={add}><Plus size={16}/> Add</button></section><section className="list">{items.length?items.map(item=><article key={item.id}><div><small>{item.type}</small><h2>{item.title}</h2></div><select value={item.status} onChange={e=>setItems(x=>x.map(i=>i.id===item.id?{...i,status:e.target.value as Media["status"]}:i))}><option>Want</option><option>In Progress</option><option>Completed</option><option>Dropped</option></select><button className="delete" onClick={()=>setItems(x=>x.filter(i=>i.id!==item.id))}><Trash2 size={15}/></button></article>):<p className="empty">Your personal list is empty.</p>}</section><p className="notice">Only use services and content you are legally permitted to access.</p></main>}
